use clap::Args;

#[derive(Args)]
pub struct DocsArgs {
    /// Path to .env.example file
    #[arg(default_value = ".env.example")]
    pub example: String,

    /// Output file (default: stdout)
    #[arg(short, long)]
    pub output: Option<String>,
}

pub fn execute(args: &DocsArgs) -> anyhow::Result<()> {
    let example_path = std::path::Path::new(&args.example);
    if !example_path.exists() {
        anyhow::bail!("Example file not found: {}", args.example);
    }

    let rules = crate::schema::load_rules_from_example(example_path)?;

    let mut markdown = String::new();
    markdown.push_str("# Environment Variables Reference\n\n");
    markdown.push_str("> Auto-generated by QuickEnv from `.env.example`\n\n");
    markdown.push_str("| Variable | Required | Default | Description |\n");
    markdown.push_str("| -------- | -------- | ------- | ----------- |\n");

    for rule in &rules {
        let required = if rule.required { "✅ Yes" } else { "❌ No" };
        let default = rule.default.as_deref().unwrap_or("-");
        let description = if rule.secret {
            format!("{} 🔒", rule.description)
        } else if rule.description.is_empty() {
            "-".to_string()
        } else {
            rule.description.clone()
        };
        // Escape pipe characters in description
        let description = description.replace('|', "\\|");
        markdown.push_str(&format!(
            "| `{}` | {} | `{}` | {} |\n",
            rule.name, required, default, description
        ));
    }

    if let Some(ref output_path) = args.output {
        std::fs::write(output_path, &markdown)?;
        println!("Generated documentation: {}", output_path);
    } else {
        print!("{}", markdown);
    }

    Ok(())
}
