use clap::Args;
use std::collections::HashSet;

#[derive(Args)]
pub struct GenerateArgs {
    /// Path to source code directory to scan
    #[arg(default_value = ".")]
    pub path: String,

    /// Output file path (default: .env.example)
    #[arg(short, long)]
    pub output: Option<String>,

    /// Include existing values from this .env file
    #[arg(short, long)]
    pub env_file: Option<String>,

    /// Write to stdout instead of file
    #[arg(short, long)]
    pub stdout: bool,
}

pub fn execute(args: &GenerateArgs) -> anyhow::Result<()> {
    let source_path = std::path::Path::new(&args.path);
    if !source_path.exists() {
        anyhow::bail!("Source path not found: {}", args.path);
    }

    // Scan source code for environment variables
    let found_vars = crate::scanner::scan_directory(source_path);
    let mut all_vars: Vec<String> = found_vars.into_iter().collect();
    all_vars.sort();

    // Load existing .env.example if present
    let existing_rules = {
        let example_path = std::path::Path::new(".env.example");
        if example_path.exists() {
            crate::schema::load_rules_from_example(example_path).unwrap_or_default()
        } else {
            vec![]
        }
    };

    // Load existing .env values if provided
    let existing_values = if let Some(ref env_path) = args.env_file {
        let path = std::path::Path::new(env_path);
        if path.exists() {
            let content = crate::envfile::read_env_file(path)?;
            Some(crate::envfile::env_to_map(&content))
        } else {
            None
        }
    } else {
        None
    };

    // Suggest new vars not in existing rules
    let known_names: HashSet<&str> = existing_rules.iter().map(|r| r.name.as_str()).collect();
    let new_vars: Vec<&str> = all_vars
        .iter()
        .filter(|v| !known_names.contains(v.as_str()))
        .map(|s| s.as_str())
        .collect();

    // Build output content
    let mut output = String::new();
    output.push_str("# Environment Variables\n");
    output.push_str("# Auto-generated by QuickEnv\n");
    output.push_str("# Add descriptions and defaults to help your team\n\n");

    if !new_vars.is_empty() {
        output.push_str("# === Detected Variables (from source code scan) ===\n");
        output.push_str("# Add descriptions and @required/@secret tags as needed\n\n");
        for var in &new_vars {
            let value = existing_values
                .as_ref()
                .and_then(|m| m.get(*var))
                .cloned()
                .unwrap_or_default();
            output.push_str(&format!(
                "# FIXME: Add description for {}\n{}={}\n\n",
                var, var, value
            ));
        }
    }

    // Add existing rules with their descriptions
    for rule in &existing_rules {
        if !rule.description.is_empty() {
            output.push_str(&format!("# {}\n", rule.description));
        } else {
            output.push_str(&format!("# {}\n", rule.name));
        }
        let value = existing_values
            .as_ref()
            .and_then(|m| m.get(&rule.name))
            .cloned()
            .or_else(|| rule.default.clone())
            .unwrap_or_default();
        output.push_str(&format!("{}={}\n\n", rule.name, value));
    }

    // Also add any vars found in existing .env that aren't in rules or scan
    if let Some(ref values) = existing_values {
        for key in values.keys() {
            if !known_names.contains(key.as_str()) && !new_vars.contains(&key.as_str()) {
                output.push_str(&format!("# {}\n{}={}\n\n", key, key, values[key]));
            }
        }
    }

    if args.stdout {
        print!("{}", output);
    } else {
        let output_path = args
            .output
            .clone()
            .unwrap_or_else(|| ".env.example".to_string());
        std::fs::write(&output_path, &output)?;
        println!("Generated: {}", output_path);
        if !new_vars.is_empty() {
            println!(
                "Found {} new environment variable(s) in source code.",
                new_vars.len()
            );
            for v in &new_vars {
                println!("  - {}", v);
            }
        }
    }

    Ok(())
}
